---
title: "Data Wrangling Test Project"
author: "Michael A. Meier"
date: "3/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


## Load tidyverse libraries


```{r}
library("tidyverse")
```


## Prepare patient data 


```{r, message=FALSE}

## import patient data 
patient_clinical_data <- read_csv(file = "data/Patient_clinical_data.csv")
# fix column names
colnames(patient_clinical_data) <- c("Study_ID", "Patient_ID", "Sex", "Age")


patient_clinical_data <- patient_clinical_data %>%
  mutate(Unique_Patient_ID = paste(Study_ID, Patient_ID, sep = "_")) %>% # create Unique_Patient_ID
  mutate(Sex = ifelse(Sex == "M", "MALE", "FEMALE")) %>% # recode values
  dplyr::select(Study_ID, Patient_ID, Unique_Patient_ID, Sex, Age) # reorder columns


head(patient_clinical_data)



```


## Prepare tissue sample metadata


```{r}

# import tissue sample metadata
tissue_sample_metadata <- read_csv(file = "data/Tissue_sample_metadata.csv")

colnames(tissue_sample_metadata) <- c("Patient_ID", "Sample_ID", "Sample_General_Pathology", "Material", "RIN", "Total_Reads")

tissue_sample_metadata <- tissue_sample_metadata %>%
  dplyr::select(Patient_ID, Sample_ID, Sample_General_Pathology) %>%
  mutate(Sample_General_Pathology = recode(Sample_General_Pathology, ## recode values
                                           `Normal` = "NORMAL",
                                           `Liver Tumor` = "PRIMARY",
                                           `Metastic Lung` = "METASTATIC"))

head(tissue_sample_metadata)

```


## Prepare assay data

```{r}

# import RNA seq data

rna_seq_data <- read_csv(file = "data/RNA_seq_data.csv")

# wrangle RNA seq data
rna_seq_data <- rna_seq_data %>%
  pivot_longer(-GeneID, names_to = "Sample_ID", values_to = "Result") %>%
  rename(Gene_Symbol = GeneID) %>%
  mutate(Material_type = "RNA") %>%
  mutate(Result_Units = "RPKM") %>%
  mutate(Status = NA) %>%
  left_join(tissue_sample_metadata, by = "Sample_ID") %>% ## add tissue sample metadata
  dplyr::select(Patient_ID, Sample_ID, Sample_General_Pathology, Material_type, Gene_Symbol, Result, Result_Units, Status)


# find missing data rows

all_samples <- c() # construct all possible unique samples

for (patient in unique(patient_clinical_data$Patient_ID)){
  patient_number <- patient %% 100 #extracts last one or two digits from patient id
  for(pathology in c("N", "T", "M")){
    for(gene_symbol in unique(rna_seq_data$Gene_Symbol)){
      sample_id <- paste0(patient,"_","CRC", patient_number, pathology, "_", gene_symbol)
      all_samples <- c(all_samples, sample_id)
    }
  }
}

observed_samples <- paste(rna_seq_data$Patient_ID, rna_seq_data$Sample_ID, rna_seq_data$Gene_Symbol, sep = "_")

missing_samples <- all_samples[!(all_samples %in% observed_samples)]

# construct and add data row for each missing sample to rna_seq_data
for (sample in missing_samples){
  Patient_ID <- strsplit(sample, "_")[[1]][1]
  Sample_ID <- strsplit(sample, "_")[[1]][2]
  Gene_Symbol <- strsplit(sample, "_")[[1]][3]
  Sample_General_Pathology <- ifelse(endsWith(Sample_ID,"N"), "NORMAL",ifelse(endsWith(Sample_ID,"M"), "METASTATIC", "PRIMARY"))
  row <- c(Patient_ID, Sample_ID, Sample_General_Pathology, "RNA", Gene_Symbol, NA, "RPKM", "NOT DONE")
  rna_seq_data <- rbind(rna_seq_data, row)
}


# import serum protein data
serum_protein_data <- read_csv(file = "data/Serum_protein_data.csv")
colnames(serum_protein_data) <- c("Patient_ID", "Sample_ID", "IL6", "IL6R")

# wrangle serum protein data
serum_protein_data <- serum_protein_data %>%
  pivot_longer(starts_with("IL"), names_to = "Gene_Symbol", values_to = "Result") %>%
  mutate(Sample_ID = toupper(Sample_ID)) %>%
  mutate(Material_type = "SERUM") %>%
  mutate(Result_Units = "g/L") %>%
  mutate(Sample_General_Pathology = NA) %>% ## need this to combine assay data
  mutate(Status = ifelse(is.na(as.numeric(Result)), "NOT DONE", NA)) %>%
  mutate(Result = ifelse(is.na(as.numeric(Result)), NA, Result)) %>%
  dplyr::select(Patient_ID, Sample_ID, Sample_General_Pathology, Material_type, Gene_Symbol, Result, Result_Units, Status)


# Combine RNA seq and serum protein results
assay_results <- rbind(rna_seq_data, serum_protein_data)

# fix data type
assay_results$Patient_ID <- as.numeric(assay_results$Patient_ID)


head(assay_results)

```

# Add assay data to patient data for final report

```{r}

report_data <- patient_clinical_data %>%
  left_join(assay_results, by = "Patient_ID") %>%
  dplyr::select(Study_ID, Patient_ID, Unique_Patient_ID, Sex, Age, Sample_ID, Sample_General_Pathology, Material_type, Gene_Symbol, Result, Result_Units, Status) %>%
  arrange(Patient_ID, Material_type, Gene_Symbol)


# fix data types
report_data$Age <- as.integer(report_data$Age)
report_data$Result <- as.numeric(report_data$Result)


# save report as csv
#write_csv(report_data, file = "report.csv")

# save as R data file
#save(report_data, file = "report.rda")


# show final report
report_data


```

